Fix debugging article about ExtJs
shopware/devdocs pull request #1115
Opened 2021-11-23 16:08 UTC by mitelg

fixes https://github.com/shopware/devdocs/issues/1074

2021-11-23 16:09 UTC, mitelg commented on source/developers-guide/debugging/index.md
> -The Chrome extension [App Inspector for Sencha™](https://chrome.google.com/webstore/detail/app-inspector-for-sencha/pbeapidedgdpniokbedbfbaacglkceae) might also be very useful.
unfortunately no longer available

2021-11-25 14:46 UTC, philipgatzka requested changes

2021-11-25 14:46 UTC, philipgatzka commented on source/developers-guide/debugging/index.md
> +e.g. in the file `/etc/php5/apache2/conf.d/20-xdebug.ini` (this might vary depending on your distribution and PHP setup).
```suggestion
e.g. in the file `/etc/php7/apache2/conf.d/20-xdebug.ini` (this might vary depending on your distribution and PHP setup).
```

2021-11-25 14:46 UTC, philipgatzka commented on source/developers-guide/debugging/index.md
> +It can be found in all common linux distributions, e.g. in Ubuntu as `php5-xdebug`.
```suggestion
It can be found in all common linux distributions, e.g. in Ubuntu as `php7-xdebug`.
```

2021-11-25 14:46 UTC, philipgatzka commented on source/developers-guide/debugging/index.md
The lines regarding ioncube compatibility can be removed completely I think, since it's not in use anymore.

2021-11-25 14:46 UTC, philipgatzka commented on source/developers-guide/debugging/index.md
> +e.g. in the file `/etc/php5/apache2/conf.d/20-xdebug.ini` (this might vary depending on your distribution and PHP setup).
I don't know whether those paths are correct, just so we don't have references to PHP5 in the documentation anymore ^^

2021-11-26 08:30 UTC, swDennis approved these changes

2021-11-26 08:35 UTC, merged